server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/board
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: bG9uZ19yYW5kb21fbGVuX3NlY3JldF9rZXlfYW5kX2tleV93aXRoX3NwZWNpYWxfY2hhcmFjdGVycw==
  expiration: 3600000 # 1시간 (밀리초)

logging:
  level:
    org.springframework.security: DEBUG